spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:~/.inspectorgit/persistence/inspectorgit
    username: test
    password: test
    driver-class-name: org.h2.Driver
